import type { Language, LandingContent } from '../types';

export const header: Record<Language, LandingContent['header']> = {
  pt: {
    brandTag: 'agenda inteligente no WhatsApp',
    navItems: [
      { label: 'Benefícios', sectionId: 'benefits' },
      { label: 'Fluxo', sectionId: 'how-it-works' },
      { label: 'Segmentos', sectionId: 'segments' },
      { label: 'FAQ', sectionId: 'faq' },
    ],
    ctaLabel: 'Entrar',
    ctaCompactLabel: 'Entrar',
    registerLabel: 'Começar grátis',
    registerCompactLabel: 'Grátis',
    clientLabel: 'Agendar horário',
    backLabel: 'Voltar para a landing',
    backCompactLabel: 'Voltar',
    languageAriaLabel: 'Selecionar idioma',
    menuAriaLabel: 'Menu principal',
    menuOpenAriaLabel: 'Abrir menu',
    menuCloseAriaLabel: 'Fechar menu',
  },
  en: {
    brandTag: 'smart scheduling on WhatsApp',
    navItems: [
      { label: 'Benefits', sectionId: 'benefits' },
      { label: 'Flow', sectionId: 'how-it-works' },
      { label: 'Segments', sectionId: 'segments' },
      { label: 'FAQ', sectionId: 'faq' },
    ],
    ctaLabel: 'Log in',
    ctaCompactLabel: 'Log in',
    registerLabel: 'Start free',
    registerCompactLabel: 'Free',
    clientLabel: 'Book appointment',
    backLabel: 'Back to landing page',
    backCompactLabel: 'Back',
    languageAriaLabel: 'Select language',
    menuAriaLabel: 'Main menu',
    menuOpenAriaLabel: 'Open menu',
    menuCloseAriaLabel: 'Close menu',
  },
  es: {
    brandTag: 'agenda inteligente en WhatsApp',
    navItems: [
      { label: 'Beneficios', sectionId: 'benefits' },
      { label: 'Flujo', sectionId: 'how-it-works' },
      { label: 'Segmentos', sectionId: 'segments' },
      { label: 'FAQ', sectionId: 'faq' },
    ],
    ctaLabel: 'Entrar',
    ctaCompactLabel: 'Entrar',
    registerLabel: 'Empezar gratis',
    registerCompactLabel: 'Gratis',
    clientLabel: 'Reservar horario',
    backLabel: 'Volver a la landing',
    backCompactLabel: 'Volver',
    languageAriaLabel: 'Seleccionar idioma',
    menuAriaLabel: 'Menú principal',
    menuOpenAriaLabel: 'Abrir menú',
    menuCloseAriaLabel: 'Cerrar menú',
  },
};
