import type { Language, LandingContent } from '../types';

export const pricing: Record<Language, LandingContent['pricing']> = {
  pt: {
    eyebrow: 'Planos e preços',
    title: 'Escolha o plano que acompanha o ritmo da sua agenda',
    description:
      'Comece com o essencial e evolua conforme sua equipe cresce. Todos os planos mantêm agenda, atendimento e automação no mesmo fluxo.',
    billingAriaLabel: 'Período de cobrança',
    monthlyLabel: 'Mensal',
    yearlyLabel: 'Anual',
    yearlyBadge: 'Economize até 25%',
    popularLabel: 'Mais popular',
    perMonthLabel: '/mês',
    billedMonthlyLabel: 'Cobrança mensal',
    billedYearlyLabel: 'Cobrado {price} por ano',
    savingsLabel: 'Economize {price} por ano',
    footnote:
      'Você pode testar o Horarius antes de assinar e mudar de plano conforme sua operação evolui.',
    plans: [
      {
        slug: 'starter',
        name: 'Starter',
        description: 'Para autônomos e pequenos negócios começarem a automatizar a agenda.',
        monthlyPrice: 110,
        yearlyPrice: 1056,
        features: [
          '1 profissional',
          'Agendamentos ilimitados',
          'Secretária IA e atendimento no WhatsApp',
          'Google Agenda e relatórios',
          '200 notificações no WhatsApp por mês',
        ],
        ctaLabel: 'Começar com Starter',
      },
      {
        slug: 'pro',
        name: 'Pro',
        description: 'Para negócios em crescimento que precisam de mais equipe e automação.',
        monthlyPrice: 150,
        yearlyPrice: 1350,
        features: [
          'Até 3 profissionais',
          'Tudo do Starter',
          'Mensagens e IA personalizadas',
          'Remarcação e cancelamento automáticos',
          'Dashboard avançado e integrações',
        ],
        ctaLabel: 'Começar com Pro',
        highlighted: true,
      },
      {
        slug: 'business',
        name: 'Equipe',
        description: 'Para operações maiores que precisam de capacidade e configuração sob medida.',
        monthlyPrice: null,
        yearlyPrice: null,
        priceLabel: 'Sob consulta',
        features: [
          'Profissionais conforme sua operação',
          'Até 10 números de WhatsApp',
          '600 notificações no WhatsApp por mês',
          'Limites e configuração sob medida',
          'Atendimento comercial para definir o plano',
        ],
        ctaLabel: 'Falar com vendas',
      },
    ],
  },
  en: {
    eyebrow: 'Plans and pricing',
    title: 'Choose the plan that keeps pace with your schedule',
    description:
      'Start with the essentials and upgrade as your team grows. Every plan keeps scheduling, service, and automation in one flow.',
    billingAriaLabel: 'Billing period',
    monthlyLabel: 'Monthly',
    yearlyLabel: 'Yearly',
    yearlyBadge: 'Save up to 25%',
    popularLabel: 'Most popular',
    perMonthLabel: '/month',
    billedMonthlyLabel: 'Billed monthly',
    billedYearlyLabel: 'Billed {price} per year',
    savingsLabel: 'Save {price} per year',
    footnote:
      'You can try Horarius before subscribing and change plans as your operation evolves.',
    plans: [
      {
        slug: 'starter',
        name: 'Starter',
        description: 'For solo professionals and small businesses ready to automate scheduling.',
        monthlyPrice: 110,
        yearlyPrice: 1056,
        features: [
          '1 professional',
          'Unlimited appointments',
          'AI secretary and WhatsApp service',
          'Google Calendar and reports',
          '200 WhatsApp notifications per month',
        ],
        ctaLabel: 'Start with Starter',
      },
      {
        slug: 'pro',
        name: 'Pro',
        description: 'For growing businesses that need more staff capacity and automation.',
        monthlyPrice: 150,
        yearlyPrice: 1350,
        features: [
          'Up to 3 professionals',
          'Everything in Starter',
          'Custom messages and AI',
          'Automatic rescheduling and cancellation',
          'Advanced dashboard and integrations',
        ],
        ctaLabel: 'Start with Pro',
        highlighted: true,
      },
      {
        slug: 'business',
        name: 'Team',
        description: 'For larger operations that need tailored capacity and configuration.',
        monthlyPrice: null,
        yearlyPrice: null,
        priceLabel: 'Contact us',
        features: [
          'Professionals based on your operation',
          'Up to 10 WhatsApp numbers',
          '600 WhatsApp notifications per month',
          'Tailored limits and configuration',
          'Sales support to define your plan',
        ],
        ctaLabel: 'Talk to sales',
      },
    ],
  },
  es: {
    eyebrow: 'Planes y precios',
    title: 'Elige el plan que acompaña el ritmo de tu agenda',
    description:
      'Empieza con lo esencial y evoluciona a medida que crece tu equipo. Todos los planes mantienen agenda, atención y automatización en un solo flujo.',
    billingAriaLabel: 'Período de facturación',
    monthlyLabel: 'Mensual',
    yearlyLabel: 'Anual',
    yearlyBadge: 'Ahorra hasta un 25%',
    popularLabel: 'Más popular',
    perMonthLabel: '/mes',
    billedMonthlyLabel: 'Facturación mensual',
    billedYearlyLabel: 'Facturado {price} por año',
    savingsLabel: 'Ahorra {price} por año',
    footnote:
      'Puedes probar Horarius antes de suscribirte y cambiar de plan a medida que evoluciona tu operación.',
    plans: [
      {
        slug: 'starter',
        name: 'Starter',
        description: 'Para profesionales independientes y pequeños negocios que quieren automatizar.',
        monthlyPrice: 110,
        yearlyPrice: 1056,
        features: [
          '1 profesional',
          'Reservas ilimitadas',
          'Secretaria IA y atención por WhatsApp',
          'Google Calendar e informes',
          '200 notificaciones de WhatsApp por mes',
        ],
        ctaLabel: 'Empezar con Starter',
      },
      {
        slug: 'pro',
        name: 'Pro',
        description: 'Para negocios en crecimiento que necesitan más equipo y automatización.',
        monthlyPrice: 150,
        yearlyPrice: 1350,
        features: [
          'Hasta 3 profesionales',
          'Todo lo de Starter',
          'Mensajes e IA personalizados',
          'Reprogramación y cancelación automáticas',
          'Panel avanzado e integraciones',
        ],
        ctaLabel: 'Empezar con Pro',
        highlighted: true,
      },
      {
        slug: 'business',
        name: 'Equipo',
        description: 'Para operaciones mayores que necesitan capacidad y configuración a medida.',
        monthlyPrice: null,
        yearlyPrice: null,
        priceLabel: 'Consultar',
        features: [
          'Profesionales según tu operación',
          'Hasta 10 números de WhatsApp',
          '600 notificaciones de WhatsApp por mes',
          'Límites y configuración a medida',
          'Atención comercial para definir el plan',
        ],
        ctaLabel: 'Hablar con ventas',
      },
    ],
  },
};
