import type { Language, LandingContent } from '../types';

/* A grade espelha `subscription_plans` do backend (slug, nome, preço e
   capacidade). Fonte da verdade é o banco — conferir com
   `GET /subscription-plans` na API antes de mexer em número aqui.
   Catálogo vigente: Agenda 49,90 · Solo 99,90 · Pro 149,90 · Empresas sob consulta.
   Anual = 10x o mensal nos três pagos, ou seja 20% de desconto.
   Agenda e Solo carregam a lista inteira porque a diferença entre eles não é
   incremental (o Agenda não tem IA, e o Solo tem 1 profissional contra os 2 do
   Agenda); Pro e Empresas listam só os deltas sob "Tudo do X, e mais:". */
export const pricing: Record<Language, LandingContent['pricing']> = {
  pt: {
    eyebrow: 'Planos e preços',
    title: 'Um plano para cada momento do seu negócio',
    description:
      'Comece organizando a agenda por R$ 49,90 e ligue a secretária de IA no WhatsApp quando fizer sentido. Agendamentos ilimitados em todos os planos.',
    includedFeaturesLabel: 'O que está incluído',
    showMoreLabel: 'Ver todas as funcionalidades',
    showLessLabel: 'Mostrar menos funcionalidades',
    billingAriaLabel: 'Período de cobrança',
    monthlyLabel: 'Mensal',
    yearlyLabel: 'Anual',
    yearlyBadge: 'Economize 20%',
    popularLabel: 'Mais popular',
    perMonthLabel: '/mês',
    billedMonthlyLabel: 'Cobrança mensal',
    billedYearlyLabel: 'Cobrado {price} por ano',
    savingsLabel: 'Economize {price} por ano',
    footnote:
      'Você pode testar o Horarius antes de assinar e mudar de plano conforme sua operação evolui.',
    assurances: [
      { icon: 'shield', label: 'API oficial do WhatsApp (Meta)' },
      { icon: 'infinity', label: 'Agendamentos ilimitados em todos os planos' },
      { icon: 'card', label: 'Teste grátis, sem cartão de crédito' },
      { icon: 'badge', label: 'Sem fidelidade — cancele quando quiser' },
    ],
    plans: [
      {
        slug: 'starter',
        name: 'Agenda',
        description:
          'Agenda completa para organizar o negócio, sem IA e sem WhatsApp.',
        monthlyPrice: 49.9,
        yearlyPrice: 478.8,
        features: [
          'Até 2 profissionais',
          'Agendamentos ilimitados',
          'Lembretes por e-mail (até 1.000 por mês)',
          'Lista de espera automática',
          'Compressão inteligente da agenda',
          'Planos recorrentes para clientes',
          'Google Agenda integrada',
          'Dashboard e relatórios',
          'Gestão de profissionais e serviços',
        ],
        ctaLabel: 'Começar com o Agenda',
      },
      {
        slug: 'solo',
        name: 'Solo',
        description:
          'Sua recepcionista de IA no WhatsApp, 24h. Para quem trabalha sozinho.',
        monthlyPrice: 99.9,
        yearlyPrice: 958.8,
        features: [
          '1 profissional',
          'Agendamentos ilimitados',
          'Secretária IA no WhatsApp 24h',
          '200 notificações no WhatsApp por mês',
          'Confirmações e lembretes automáticos',
          'Remarcação e cancelamento automáticos',
          'Lista de espera automática',
          'Compressão inteligente da agenda',
          'Prioridade para horários do mesmo dia',
          'Campanhas e reativação de clientes',
          'Planos recorrentes para clientes',
          'Mensagens e IA personalizadas',
          'Google Agenda integrada',
          'Dashboard avançado e relatórios',
          'Resumo matinal da operação',
        ],
        ctaLabel: 'Começar com o Solo',
      },
      {
        slug: 'pro',
        name: 'Pro',
        description:
          'Para negócios em crescimento que precisam de mais equipe e volume.',
        monthlyPrice: 149.9,
        yearlyPrice: 1438.8,
        baseline: 'Tudo do Solo, e mais:',
        features: [
          'Até 3 profissionais',
          '600 notificações no WhatsApp por mês',
          'Agenda e horários por profissional',
          'Serviços e durações por profissional',
        ],
        ctaLabel: 'Começar com o Pro',
        highlighted: true,
      },
      {
        slug: 'business',
        name: 'Empresas',
        description:
          'Para equipes maiores e redes que precisam de capacidade sob medida.',
        monthlyPrice: null,
        yearlyPrice: null,
        priceLabel: 'Sob consulta',
        baseline: 'Tudo do Pro, e mais:',
        features: [
          'Profissionais conforme sua operação',
          'Volume de notificações sob consulta',
          'Limites e configuração sob medida',
        ],
        ctaLabel: 'Falar com vendas',
      },
    ],
  },
  en: {
    eyebrow: 'Plans and pricing',
    title: 'A plan for every stage of your business',
    description:
      'Start by getting the calendar in order, then switch on the WhatsApp AI receptionist when it makes sense. Unlimited appointments on every plan.',
    includedFeaturesLabel: 'What is included',
    showMoreLabel: 'View all features',
    showLessLabel: 'Show fewer features',
    billingAriaLabel: 'Billing period',
    monthlyLabel: 'Monthly',
    yearlyLabel: 'Yearly',
    yearlyBadge: 'Save 20%',
    popularLabel: 'Most popular',
    perMonthLabel: '/month',
    billedMonthlyLabel: 'Billed monthly',
    billedYearlyLabel: 'Billed {price} per year',
    savingsLabel: 'Save {price} per year',
    footnote:
      'You can try Horarius before subscribing and change plans as your operation evolves.',
    assurances: [
      { icon: 'shield', label: 'Official WhatsApp API (Meta)' },
      { icon: 'infinity', label: 'Unlimited appointments on every plan' },
      { icon: 'card', label: 'Free to try, no credit card' },
      { icon: 'badge', label: 'No lock-in — cancel anytime' },
    ],
    plans: [
      {
        slug: 'starter',
        name: 'Calendar',
        description:
          'A complete calendar to run the business — no AI and no WhatsApp.',
        monthlyPrice: 49.9,
        yearlyPrice: 478.8,
        features: [
          'Up to 2 professionals',
          'Unlimited appointments',
          'Email reminders (up to 1,000 per month)',
          'Automated waitlist',
          'Smart schedule compression',
          'Recurring customer plans',
          'Google Calendar integration',
          'Dashboard and reports',
          'Professionals and services management',
        ],
        ctaLabel: 'Start with Calendar',
      },
      {
        slug: 'solo',
        name: 'Solo',
        description:
          'Your AI receptionist on WhatsApp, 24/7. For people working on their own.',
        monthlyPrice: 99.9,
        yearlyPrice: 958.8,
        features: [
          '1 professional',
          'Unlimited appointments',
          '24/7 AI secretary on WhatsApp',
          '200 WhatsApp notifications per month',
          'Automatic confirmations and reminders',
          'Automatic rescheduling and cancellation',
          'Automated waitlist',
          'Smart schedule compression',
          'Same-day slot priority',
          'Customer outreach and reactivation',
          'Recurring customer plans',
          'Custom messages and AI',
          'Google Calendar integration',
          'Advanced dashboard and reports',
          'Morning operation summary',
        ],
        ctaLabel: 'Start with Solo',
      },
      {
        slug: 'pro',
        name: 'Pro',
        description:
          'For growing businesses that need a bigger team and more volume.',
        monthlyPrice: 149.9,
        yearlyPrice: 1438.8,
        baseline: 'Everything in Solo, plus:',
        features: [
          'Up to 3 professionals',
          '600 WhatsApp notifications per month',
          'Calendar and hours per professional',
          'Services and durations per professional',
        ],
        ctaLabel: 'Start with Pro',
        highlighted: true,
      },
      {
        slug: 'business',
        name: 'Teams',
        description:
          'For larger teams and chains that need tailor-made capacity.',
        monthlyPrice: null,
        yearlyPrice: null,
        priceLabel: 'Contact us',
        baseline: 'Everything in Pro, plus:',
        features: [
          'Professionals to match your operation',
          'Notification volume on request',
          'Tailor-made limits and configuration',
        ],
        ctaLabel: 'Talk to sales',
      },
    ],
  },
  es: {
    eyebrow: 'Planes y precios',
    title: 'Un plan para cada momento de tu negocio',
    description:
      'Empieza organizando la agenda y activa la recepcionista de IA en WhatsApp cuando tenga sentido. Reservas ilimitadas en todos los planes.',
    includedFeaturesLabel: 'Qué está incluido',
    showMoreLabel: 'Ver todas las funciones',
    showLessLabel: 'Mostrar menos funciones',
    billingAriaLabel: 'Período de facturación',
    monthlyLabel: 'Mensual',
    yearlyLabel: 'Anual',
    yearlyBadge: 'Ahorra un 20%',
    popularLabel: 'Más popular',
    perMonthLabel: '/mes',
    billedMonthlyLabel: 'Facturación mensual',
    billedYearlyLabel: 'Facturado {price} por año',
    savingsLabel: 'Ahorra {price} por año',
    footnote:
      'Puedes probar Horarius antes de suscribirte y cambiar de plan a medida que evoluciona tu operación.',
    assurances: [
      { icon: 'shield', label: 'API oficial de WhatsApp (Meta)' },
      { icon: 'infinity', label: 'Reservas ilimitadas en todos los planes' },
      { icon: 'card', label: 'Prueba gratis, sin tarjeta de crédito' },
      { icon: 'badge', label: 'Sin permanencia — cancela cuando quieras' },
    ],
    plans: [
      {
        slug: 'starter',
        name: 'Agenda',
        description:
          'Agenda completa para organizar el negocio, sin IA y sin WhatsApp.',
        monthlyPrice: 49.9,
        yearlyPrice: 478.8,
        features: [
          'Hasta 2 profesionales',
          'Reservas ilimitadas',
          'Recordatorios por correo (hasta 1.000 al mes)',
          'Lista de espera automática',
          'Compresión inteligente de la agenda',
          'Planes recurrentes para clientes',
          'Google Calendar integrado',
          'Panel e informes',
          'Gestión de profesionales y servicios',
        ],
        ctaLabel: 'Empezar con Agenda',
      },
      {
        slug: 'solo',
        name: 'Solo',
        description:
          'Tu recepcionista de IA en WhatsApp, 24 h. Para quien trabaja solo.',
        monthlyPrice: 99.9,
        yearlyPrice: 958.8,
        features: [
          '1 profesional',
          'Reservas ilimitadas',
          'Secretaria IA en WhatsApp 24 h',
          '200 notificaciones de WhatsApp al mes',
          'Confirmaciones y recordatorios automáticos',
          'Reprogramación y cancelación automáticas',
          'Lista de espera automática',
          'Compresión inteligente de la agenda',
          'Prioridad para horarios del mismo día',
          'Campañas y reactivación de clientes',
          'Planes recurrentes para clientes',
          'Mensajes e IA personalizados',
          'Google Calendar integrado',
          'Panel avanzado e informes',
          'Resumen matinal de la operación',
        ],
        ctaLabel: 'Empezar con Solo',
      },
      {
        slug: 'pro',
        name: 'Pro',
        description:
          'Para negocios en crecimiento que necesitan más equipo y volumen.',
        monthlyPrice: 149.9,
        yearlyPrice: 1438.8,
        baseline: 'Todo lo de Solo, y además:',
        features: [
          'Hasta 3 profesionales',
          '600 notificaciones de WhatsApp al mes',
          'Agenda y horarios por profesional',
          'Servicios y duraciones por profesional',
        ],
        ctaLabel: 'Empezar con Pro',
        highlighted: true,
      },
      {
        slug: 'business',
        name: 'Empresas',
        description:
          'Para equipos grandes y cadenas que necesitan capacidad a medida.',
        monthlyPrice: null,
        yearlyPrice: null,
        priceLabel: 'Consultar',
        baseline: 'Todo lo de Pro, y además:',
        features: [
          'Profesionales según tu operación',
          'Volumen de notificaciones a consultar',
          'Límites y configuración a medida',
        ],
        ctaLabel: 'Hablar con ventas',
      },
    ],
  },
};
