import type { Language, LandingContent } from '../types';

/* Regras da grade: o Starter carrega a lista completa de funcionalidades (as
   cinco primeiras ficam visíveis, o resto atrás do "ver todas"); Pro e Equipe
   listam só os deltas sob o baseline "Tudo do X, e mais:". Assim a diferença
   de preço é legível de relance — todos os planos têm o produto inteiro, o
   que muda é capacidade. */
export const pricing: Record<Language, LandingContent['pricing']> = {
  pt: {
    eyebrow: 'Planos e preços',
    title: 'O produto inteiro em todos os planos',
    description:
      'IA no WhatsApp, agendamentos ilimitados e todas as automações estão em qualquer plano — o que muda é o tamanho da equipe e a capacidade de atendimento.',
    includedFeaturesLabel: 'O que está incluído',
    showMoreLabel: 'Ver todas as funcionalidades',
    showLessLabel: 'Mostrar menos funcionalidades',
    billingAriaLabel: 'Período de cobrança',
    monthlyLabel: 'Mensal',
    yearlyLabel: 'Anual',
    yearlyBadge: 'Economize até 25%',
    popularLabel: 'Mais popular',
    perMonthLabel: '/mês',
    billedMonthlyLabel: 'Cobrança mensal',
    billedYearlyLabel: 'Cobrado {price} por ano',
    savingsLabel: 'Economize {price} por ano',
    footnote:
      'Você pode testar o Horarius antes de assinar e mudar de plano conforme sua operação evolui.',
    assurances: [
      { icon: 'shield', label: 'API oficial do WhatsApp (Meta)' },
      { icon: 'infinity', label: 'Agendamentos ilimitados em todos os planos' },
      { icon: 'card', label: 'Teste grátis, sem cartão de crédito' },
      { icon: 'badge', label: 'Sem fidelidade — cancele quando quiser' },
    ],
    plans: [
      {
        slug: 'starter',
        name: 'Starter',
        description: 'Para autônomos e pequenos negócios começarem a automatizar a agenda.',
        monthlyPrice: 110,
        yearlyPrice: 1056,
        features: [
          '1 profissional',
          'Agendamentos ilimitados',
          'Secretária IA no WhatsApp',
          'Confirmações e lembretes automáticos',
          'Atendimento automático 24 horas',
          'Remarcação e cancelamento automáticos',
          'Avaliações de clientes pós-atendimento',
          '200 notificações no WhatsApp por mês',
          'Lista de espera automática',
          'Compressão inteligente da agenda',
          'Prioridade para horários do mesmo dia',
          'Google Agenda integrada',
          'Campanhas e reativação de clientes',
          'Planos recorrentes para clientes',
          'Mensagens e IA personalizadas',
          'Dashboard e relatórios',
          'Resumo matinal da operação',
          'Gestão de profissionais e serviços',
        ],
        ctaLabel: 'Começar com Starter',
      },
      {
        slug: 'pro',
        name: 'Pro',
        description: 'Para negócios em crescimento que precisam de mais equipe e automação.',
        monthlyPrice: 150,
        yearlyPrice: 1350,
        baseline: 'Tudo do Starter, e mais:',
        features: [
          'Até 3 profissionais',
          '600 notificações no WhatsApp por mês',
          'Agenda e horários por profissional',
          'Serviços e durações por profissional',
        ],
        ctaLabel: 'Começar com Pro',
        highlighted: true,
      },
      {
        slug: 'business',
        name: 'Equipe',
        description: 'Para operações maiores que precisam de capacidade e configuração sob medida.',
        monthlyPrice: null,
        yearlyPrice: null,
        priceLabel: 'Sob consulta',
        baseline: 'Tudo do Pro, e mais:',
        features: [
          'Profissionais conforme sua operação',
          'Volume de notificações sob consulta',
          'Limites e configuração sob medida',
        ],
        ctaLabel: 'Falar com vendas',
      },
    ],
  },
  en: {
    eyebrow: 'Plans and pricing',
    title: 'The whole product on every plan',
    description:
      'WhatsApp AI, unlimited appointments and every automation are included in any plan — what changes is team size and service capacity.',
    includedFeaturesLabel: 'What is included',
    showMoreLabel: 'View all features',
    showLessLabel: 'Show fewer features',
    billingAriaLabel: 'Billing period',
    monthlyLabel: 'Monthly',
    yearlyLabel: 'Yearly',
    yearlyBadge: 'Save up to 25%',
    popularLabel: 'Most popular',
    perMonthLabel: '/month',
    billedMonthlyLabel: 'Billed monthly',
    billedYearlyLabel: 'Billed {price} per year',
    savingsLabel: 'Save {price} per year',
    footnote:
      'You can try Horarius before subscribing and change plans as your operation evolves.',
    assurances: [
      { icon: 'shield', label: 'Official WhatsApp API (Meta)' },
      { icon: 'infinity', label: 'Unlimited appointments on every plan' },
      { icon: 'card', label: 'Free to try, no credit card' },
      { icon: 'badge', label: 'No lock-in — cancel anytime' },
    ],
    plans: [
      {
        slug: 'starter',
        name: 'Starter',
        description: 'For solo professionals and small businesses ready to automate scheduling.',
        monthlyPrice: 110,
        yearlyPrice: 1056,
        features: [
          '1 professional',
          'Unlimited appointments',
          'AI secretary on WhatsApp',
          'Automatic confirmations and reminders',
          '24/7 automated service',
          'Automatic rescheduling and cancellation',
          'Post-visit customer reviews',
          '200 WhatsApp notifications per month',
          'Automated waitlist',
          'Smart schedule compression',
          'Same-day slot priority',
          'Google Calendar integration',
          'Customer outreach and reactivation',
          'Recurring customer plans',
          'Custom messages and AI',
          'Dashboard and reports',
          'Morning operation summary',
          'Staff and service management',
        ],
        ctaLabel: 'Start with Starter',
      },
      {
        slug: 'pro',
        name: 'Pro',
        description: 'For growing businesses that need more staff capacity and automation.',
        monthlyPrice: 150,
        yearlyPrice: 1350,
        baseline: 'Everything in Starter, plus:',
        features: [
          'Up to 3 professionals',
          '600 WhatsApp notifications per month',
          'Per-professional calendar and hours',
          'Per-professional services and durations',
        ],
        ctaLabel: 'Start with Pro',
        highlighted: true,
      },
      {
        slug: 'business',
        name: 'Team',
        description: 'For larger operations that need tailored capacity and configuration.',
        monthlyPrice: null,
        yearlyPrice: null,
        priceLabel: 'Contact us',
        baseline: 'Everything in Pro, plus:',
        features: [
          'Professionals based on your operation',
          'Notification volume on request',
          'Tailored limits and configuration',
        ],
        ctaLabel: 'Talk to sales',
      },
    ],
  },
  es: {
    eyebrow: 'Planes y precios',
    title: 'El producto completo en todos los planes',
    description:
      'IA en WhatsApp, reservas ilimitadas y todas las automatizaciones están en cualquier plan — lo que cambia es el tamaño del equipo y la capacidad de atención.',
    includedFeaturesLabel: 'Qué está incluido',
    showMoreLabel: 'Ver todas las funciones',
    showLessLabel: 'Mostrar menos funciones',
    billingAriaLabel: 'Período de facturación',
    monthlyLabel: 'Mensual',
    yearlyLabel: 'Anual',
    yearlyBadge: 'Ahorra hasta un 25%',
    popularLabel: 'Más popular',
    perMonthLabel: '/mes',
    billedMonthlyLabel: 'Facturación mensual',
    billedYearlyLabel: 'Facturado {price} por año',
    savingsLabel: 'Ahorra {price} por año',
    footnote:
      'Puedes probar Horarius antes de suscribirte y cambiar de plan a medida que evoluciona tu operación.',
    assurances: [
      { icon: 'shield', label: 'API oficial de WhatsApp (Meta)' },
      { icon: 'infinity', label: 'Reservas ilimitadas en todos los planes' },
      { icon: 'card', label: 'Prueba gratis, sin tarjeta de crédito' },
      { icon: 'badge', label: 'Sin permanencia — cancela cuando quieras' },
    ],
    plans: [
      {
        slug: 'starter',
        name: 'Starter',
        description: 'Para profesionales independientes y pequeños negocios que quieren automatizar.',
        monthlyPrice: 110,
        yearlyPrice: 1056,
        features: [
          '1 profesional',
          'Reservas ilimitadas',
          'Secretaria IA en WhatsApp',
          'Confirmaciones y recordatorios automáticos',
          'Atención automática las 24 horas',
          'Reprogramación y cancelación automáticas',
          'Valoraciones de clientes tras la visita',
          '200 notificaciones de WhatsApp por mes',
          'Lista de espera automática',
          'Compresión inteligente de la agenda',
          'Prioridad para horarios del mismo día',
          'Integración con Google Calendar',
          'Campañas y reactivación de clientes',
          'Planes recurrentes para clientes',
          'Mensajes e IA personalizados',
          'Panel e informes',
          'Resumen matinal de la operación',
          'Gestión de profesionales y servicios',
        ],
        ctaLabel: 'Empezar con Starter',
      },
      {
        slug: 'pro',
        name: 'Pro',
        description: 'Para negocios en crecimiento que necesitan más equipo y automatización.',
        monthlyPrice: 150,
        yearlyPrice: 1350,
        baseline: 'Todo lo de Starter, y además:',
        features: [
          'Hasta 3 profesionales',
          '600 notificaciones de WhatsApp por mes',
          'Agenda y horarios por profesional',
          'Servicios y duraciones por profesional',
        ],
        ctaLabel: 'Empezar con Pro',
        highlighted: true,
      },
      {
        slug: 'business',
        name: 'Equipo',
        description: 'Para operaciones mayores que necesitan capacidad y configuración a medida.',
        monthlyPrice: null,
        yearlyPrice: null,
        priceLabel: 'Consultar',
        baseline: 'Todo lo de Pro, y además:',
        features: [
          'Profesionales según tu operación',
          'Volumen de notificaciones a consultar',
          'Límites y configuración a medida',
        ],
        ctaLabel: 'Hablar con ventas',
      },
    ],
  },
};
